Algoritmo "semnome"
// Autor(a)    : Kaique barbosa
// Data atual  : 21/03/2023
Var
n1, n2, area: real


Inicio
escreval("Digite o tamanho da base do triangulo")
leia(n1)
escreval("Digite o tamanho da altura do triangulo")
leia(n2)
escreva("----------------------------------")

area <- (n1 * n2) / 2;

escreval()

escreval("Base: ", n1)
escreval("Altura: ", n2)
escreval("Área: ", area)


Fimalgoritmo